# Generated by Django 4.2 on 2023-04-16 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['-year']},
        ),
        migrations.AlterField(
            model_name='carimage',
            name='car',
            field=models.ForeignKey(blank=True, default='photos/default.jpg', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='images', to='cars.car'),
        ),
    ]
